/**
 * apex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: mariuskoehler@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpStatusCode } from './httpStatusCode';


export interface AuthenticationError { 
    name: string;
    message: string;
    stack?: string;
    status: HttpStatusCode;
}
export namespace AuthenticationError {
}


